language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION = 'pypy' ]]; then grep -v ^gevent requirements.txt > requirements.txt; fi
  - pip install -r requirements.txt
# command to run tests
script: nosetests